#!/bin/sh
X=$(xdotool getmouselocation | grep -Po '(?<=^x:)\w+')
array=( "0" "1920" "3840" )
array2=( "1920" "3840" "5760" )
array3=( "2880" "4800" "960" )
if ! nvidia-settings --query CurrentMetaMode | grep DPY-4 > /dev/null; then
array3=( "2880" "960" )
fi
for i in ${!array[*]}; do
if [ $X -gt ${array[i]} -a $X -lt ${array2[i]} ]; then
	xdotool mousemove --sync ${array3[i]} 540
fi
done
