#!/bin/bash
conf=$HOME/.config/screenblank.conf

# Default timings in minutes
Default_blank="10"
Default_blanklock=".5"
Default_lock="30"
Default_suspend="60"

set_conf() {
	if [[ ! -e $conf ]]; then
		cat <<-EOF >> $conf
		screensaver=on
		autosuspend=on
		autolock=on
		blank=$Default_blank
		blanklock=$Default_blanklock
		lock=$Default_lock
		suspend=$Default_suspend
		EOF
	elif xset -q | grep "yes" &> /dev/null; then
		xset s 0 0
		xset s noblank
		xset s noexpose
		xset dpms 0 0 0
	fi
}

set_times() {
	. $conf
	times=( "$blank" "$blanklock" "$lock" "$suspend" )
	CHK1=${times[@]}
	CHK2=${timesCHK[@]}
	if [ "$CHK1" != "$CHK2" ]; then
		timesMS=() timesCHK=()
		for i in ${!times[*]}; do
			MS=$(echo "${times[i]}*60000-2000" | bc -l)
			timesMS+=(${MS%.*}) timesCHK+=(${times[i]})
		done
	fi
}

if_video() {
	media=( "youtube\|vimeo\|twitch" "bomi" "mpv")
	media2=( "Vivaldi" "bomi" "mpv")
	for i in ${!media[*]}; do
		if [[ $(wmctrl -l | grep -i "${media[i]}") ]] && \
		[[ $(pacmd list-sink-inputs | grep -B12 ${media2[i]} | grep RUNNING) ]]
		then vid_playing=1; break
		else vid_playing=0
		fi
	done
}

resetidle() {
	xdotool mousemove_relative --sync -- 25 25 
	xdotool mousemove_relative --sync -- -25 -25
}

update() {
	sed -i "s/^\($key=\).*/\1$value/" $conf
}

killtv() {
	DVI="DPY-0: nvidia-auto-select +1920+0 {ForceCompositionPipeline=On}"
	HDMI="DPY-1: nvidia-auto-select +0+0 {ForceCompositionPipeline=On}"
	[[ $(nvidia-settings --query CurrentMetaMode | grep +3840) ]] && \
	nvidia-settings --assign CurrentMetaMode="$DVI, $HDMI"
}

bls() {
	scrot /tmp/screen.png
	betterlockscreen -u /tmp/screen.png
	betterlockscreen -l dimblur &
}

notify() {
	echo "$message"
	[[ $(pgrep xfce4-notifyd) ]] && \
	notify-send "$message"
}

status() {
	cat <<-EOH
	Screensaver is $screensaver
	AutoLock is $autolock
	AutoSuspend is $autosuspend
	-----------------------
	Blank Screen at $blank Mins
	Blank LockScreen at $blanklock Mins
	Lock at $lock Mins
	Suspend at $suspend Mins

	EOH
}

usage() {
	cat <<-EOH
	screenblank: Screensaver script for finer control over xset. (in my opinion)
	
	Usage:
	screenblank
	run script without options to toggle on/off
			
	screenblank -ts | --toggle_suspend
	toggle AutoSuspend on/off

	screenblank -tl | --toggle_lock
	toggle AutoLock on/off

	screenblank -b | --blank
	blank the screen

	screenblank -l | --lock
	lock the screen with "betterlockscreen"

	screenblank -s | --status
	check current configuration

	screenblank -h | --help
	view usage (this)

	screenblank -r | --reset
	reset the configuration

	screenblank -ab | --adjust_blank
	adjust Screen Blank time in minutes

	screenblank -alb | --adjust_ls_blank
	adjust LockScreen blank time in minutes

	screenblank -as | --adjust_suspend
	adjust Suspend time in minutes

	screenblank -al | --adjust_lock
	adjust Suspend time in minutes
	EOH
}

vid_playing=0
set_conf
. $conf

# Options
if [[ -z $1 ]]; then
     if [[ ! $(pgrep -c screenblank) == "2" ]]; then
        message="Screensaver Enabled" notify
        key=screensaver value=on update
    else
		message="Screensaver Disabled" notify
		key=screensaver value=off update
		pkill -x screenblank
    fi
elif [[ $# == 1 ]];then
	case "$1" in
		-ts | --toggle_suspend)
			if [[ $autosuspend == on ]]; then
				message="AutoSuspend Disabled" notify
				key=autosuspend value=off update
			else
				message="AutoSuspend Enabled" notify
				key=autosuspend value=on update
			fi
			;;
		-tl | --toggle_lock)
			if [[ $autolock == on ]]; then
				message="AutoLock Disabled" notify
				key=autolock value=off update
			else
				message="AutoLock Enabled" notify
				key=autolock value=on update
			fi
			;;
		-b | --blank)
			sleep 2
			xset dpms force off
			;;
		-l | --lock)
			bls
			;;
		-s | --status)
			message="$(status)" notify
			;;
		-h | --help)
			usage
			;;
		-r | --reset)
			rm $conf
			echo "conf reset"
			;;
		--b4suspend)
			killtv
			bls
			;;
		*)
			echo -e "(((invalid argument)))\n"
			usage
			exit 1
			;;
	esac
	exit 0
elif [[ $# == 2 ]];then
	[[ ! $2 =~ ^[.0-9]+$ ]] && {
	echo -e "(((invalid argument)))\n"
	usage
	exit 1;}
	case "$1" in
		-ab | --adjust_blank)
			if echo "$2 >= $suspend" | bc -l | grep -q 1; then
			echo "Can't be set higher than Suspend time"
			exit 1
			fi
			echo "Screen blank set at $2 mins"
			key=blank value=$2 update
			;;
		-alb | --adjust_ls_blank)
			if echo "$2 >= $suspend" | bc -l | grep -q 1; then
			echo "Can't be set higher than Suspend time"
			exit 1
			fi
			echo "LockScreen blank set at $2 mins"
			key=blanklock value=$2 update
			;;
		-al | --adjust_lock)
			if echo "$2 >= $suspend" | bc -l | grep -q 1; then
			echo "Can't be set higher than Suspend time"
			exit 1
			elif echo "$2 <= $blank" | bc -l | grep -q 1; then
			echo "Can't be set lower than Blank time"
			exit 1
			fi
			echo "AutoLock set at $2 mins"
			key=lock value=$2 update
			;;
		-as | --adjust_suspend)
			echo "AutoSuspend set at $2 mins"
			key=suspend value=$2 update
			;;
		*)
			echo -e "(((invalid argument)))\n"
			usage
			exit 1
			;;
	esac
	exit 0
else
	echo -e "(((invalid argument)))\n" 
	usage
	exit 1
fi

# Running it
while true; do
	sleep 2
	echo "$(xprintidle)"
	if [[ $(xset -q  | grep -i "monitor is off") ]]; then
		if_video; [[ $vid_playing == 0 ]] && {
		[[ $autolock == on ]] && [[ "$(xprintidle)" -ge "${timesMS[2]}" ]] && bls
		[[ $autosuspend == on ]] && [[ "$(xprintidle)" -ge "${timesMS[3]}" ]] && {
			systemctl suspend && resetidle
			until xset -q  | grep -i "monitor is on"; do xset dpms force on; done
		}
		continue
		}
	elif [[ $(pgrep i3lock) ]]; then
		[[ "$(xprintidle)" -le "${timesMS[1]}" ]] && continue
	else
		[[ $vid_playing == 1 ]] && {
			if_video; [[ $vid_playing == 0 ]] && resetidle
			echo "Video is playing"
			continue
		}
		set_conf; set_times; if_video;
		[[ "$(xprintidle)" -le "${timesMS[0]}" ]] && continue
	fi
	xset dpms force off
done
