#!/bin/bash
conf=$HOME/.config/screenblank.conf

set_conf() {
	[[ ! -e $conf ]] && {
    cat <<-EOF >> $conf
    screenblank=on
    autosuspend=on
    autolock=on
    blank="10"
    blanklock=".5"
    lock="30"
    suspend="60"
	EOF
    }
	[[ $(xset -q) == *"yes"* ]] && {
	xset s 0 0
	xset s noblank
	xset s noexpose
	xset dpms 0 0 0
	}
}

set_times() {
	. $conf
	times=( "$blank" "$blanklock" "$lock" "$suspend" )
	CHK1=${times[@]}
	CHK2=${timesCHK[@]}
	if [ "$CHK1" != "$CHK2" ]; then
		timesMS=() timesCHK=()
		for i in ${!times[*]}; do
			MS=$(echo "${times[i]}*60000-2000" | bc -l)
			timesMS+=(${MS%.*}) timesCHK+=(${times[i]})
		done
	fi
}

if_video() {
	media=( "youtube\|vimeo\|twitch" "bomi" "mpv" )
	media2=( "Vivaldi\|Chromium" "bomi" "mpv" )
	for i in ${!media[*]}; do
		[[ $(pacmd list-sink-inputs | grep -B12 ${media2[i]}) == *"RUNNING"* ]] || continue
		[[ $(wmctrl -l | grep -i ${media[i]}) ]] && return 0
	done
	return 1
}

resetidle() {
	xdotool mousemove_relative --sync -- 25 25
	xdotool mousemove_relative --sync -- -25 -25
}

update() {
	sed -i "s/^\($1=\).*/\1$2/" $conf
}

sxl() {
	[[ $(nvidia-settings --query CurrentMetaMode) = *DPY-2* ]] && \
    $HOME/scripts/tv-toggle &
    xfconf-query xfconf-query -c xfce4-notifyd -p /do-not-disturb -s true
	sxlock && \
	xfconf-query xfconf-query -c xfce4-notifyd -p /do-not-disturb -s false
}

notify() {
	echo "$1"
	[[ $(pgrep xfce4-notifyd) ]] && \
	notify-send "$1"
}

status() {
	if_video && \
	vid_playing="playing" || \
	vid_playing="not playing"

	cat <<-EOH
	screenblank is $screenblank
	AutoLock is $autolock
	AutoSuspend is $autosuspend
	Video is $vid_playing
	-----------------------
	Blank Screen at $blank Mins
	Blank LockScreen at $blanklock Mins
	Lock at $lock Mins
	Suspend at $suspend Mins

	EOH
}

usage() {
	cat <<-EOH
	screenblank: DPMS bash script for finer control over xset. (in my opinion)

	Usage:
	screenblank
	run script without options to toggle on/off

	screenblank -ts | --toggle_suspend
	toggle AutoSuspend on/off

	screenblank -tl | --toggle_lock
	toggle AutoLock on/off

	screenblank -b | --blank
	blank the screen

	screenblank -l | --lock
	lock the screen with "betterlockscreen"

	screenblank -s | --status
	check current configuration

	screenblank -h | --help
	view usage (this)

	screenblank -r | --reset
	reset the configuration

	screenblank -ab | --adjust_blank
	adjust Screen Blank time in minutes

	screenblank -alb | --adjust_ls_blank
	adjust LockScreen blank time in minutes

	screenblank -as | --adjust_suspend
	adjust Suspend time in minutes

	screenblank -al | --adjust_lock
	adjust Suspend time in minutes
	EOH
}

set_conf
. $conf

# Options
if [[ -z $1 ]]; then
     if [[ ! $(pgrep -c screenblank) == "2" ]]; then
        notify "screenblank Enabled"
        update screenblank on
    else
		notify "screenblank Disabled"
		update screenblank off
		pkill -x screenblank
    fi
elif [[ $# == 1 ]];then
	case "$1" in
		-ts | --toggle_suspend)
			if [[ $autosuspend == on ]]; then
				notify "AutoSuspend Disabled"
				update autosuspend off
			else
				notify "AutoSuspend Enabled"
				update autosuspend on
			fi
			;;
		-tl | --toggle_lock)
			if [[ $autolock == on ]]; then
				notify "AutoLock Disabled"
				update autolock off
			else
				notify "AutoLock Enabled"
				update autolock on
			fi
			;;
		-b | --blank)
			sleep 2
			xset dpms force off
			;;
		-l | --lock)
			[[ ! $(pidof sxlock) ]] && (sxl) &
			;;
		-s | --status)
			notify "$(status)"
			;;
		-h | --help)
			usage
			;;
		-r | --reset)
			rm $conf
			echo "conf reset"
			;;
		*)
			echo -e "(((invalid argument)))\n"
			usage
			exit 1
			;;
	esac
	exit 0
elif [[ $# == 2 ]];then
	[[ ! $2 =~ ^[.0-9]+$ ]] && {
	echo -e "(((invalid argument)))\n"
	usage
	exit 1;}
	case "$1" in
		-ab | --adjust_blank)
			if echo "$2 >= $suspend" | bc -l | grep -q 1; then
			echo "Can't be set higher than Suspend time"
			exit 1
			fi
			echo "Screen blank set at $2 mins"
			update blank $2
			;;
		-alb | --adjust_ls_blank)
			if echo "$2 >= $suspend" | bc -l | grep -q 1; then
			echo "Can't be set higher than Suspend time"
			exit 1
			fi
			echo "LockScreen blank set at $2 mins"
			update blanklock $2
			;;
		-al | --adjust_lock)
			if echo "$2 >= $suspend" | bc -l | grep -q 1; then
			echo "Can't be set higher than Suspend time"
			exit 1
			elif echo "$2 <= $blank" | bc -l | grep -q 1; then
			echo "Can't be set lower than Blank time"
			exit 1
			fi
			echo "AutoLock set at $2 mins"
			update lock $2
			;;
		-as | --adjust_suspend)
			echo "AutoSuspend set at $2 mins"
			update suspend $2
			;;
		*)
			echo -e "(((invalid argument)))\n"
			usage
			exit 1
			;;
	esac
	exit 0
else
	echo -e "(((invalid argument)))\n"
	usage
	exit 1
fi

# Running it
while true; do
	read -t 2 <> <(:)
	echo "$(xprintidle)"
	if [[ $(xset -q) == *"Monitor is Off"* ]]; then
		if_video || {
			[[ $autolock == on ]] && \
			[[ "$(xprintidle)" -ge "${timesMS[2]}" ]] && \
			[[ ! $(pidof sxlock) ]] && (sxl) &
			[[ $autosuspend == on ]] && \
			[[ "$(xprintidle)" -ge "${timesMS[3]}" ]] && {
				systemctl suspend && resetidle
				until [[ $(xset -q) == *"Monitor is On"* ]]; do
				xset dpms force on
				done
			}
		continue
		}
	elif [[ $(pidof sxlock) ]]; then
		[[ "$(xprintidle)" -le "${timesMS[1]}" ]] && continue
	else
		while if_video; do
			echo "Video is playing"
			read -t 2 <> <(:)
			if_video || resetidle
			[[ $(pidof sxlock) ]] && break
		done
		set_conf; set_times;
		[[ "$(xprintidle)" -le "${timesMS[0]}" ]] && continue
	fi
	xset dpms force off
done

