#!/bin/bash
type=( ".mkv" ".mp4" ".avi" )

help() {
	cat <<-EOH
	sendvid: Script to move my shitty animu.
	
	Usage:
	
	sendvid "folder_with_animu" "folder_to_send_animu"
	sendvid "-t" to use current folder
	EOH
    exit 1
}

if [ $# -ne 2 ]
then help;
elif [ $1 == '-t' ]
then place="$PWD";
elif [ -d $1 ]
then place="$1";
else help;
fi

for i in ${!type[*]}; do
	if ls "$place" | grep -i ${type[i]}
	then find "$place" -maxdepth 1 -type f \( -iname \*${type[i]} \) -print0 | xargs -0 mv -t "$2";
	fi
done
