#!/bin/sh
DVI="DPY-0: nvidia-auto-select +1920+0 {ForceCompositionPipeline=On}"
HDMI="DPY-1: nvidia-auto-select +0+0 {ForceCompositionPipeline=On}"
TV="DPY-4: nvidia-auto-select +3840+0 {ForceCompositionPipeline=On}"
polyrestart=$($HOME/.config/polybar/launch.sh &>/dev/null &)
notifyrestart=$(pkill xfce4-notifyd; /usr/lib/xfce4/notifyd/xfce4-notifyd &>/dev/null &)

if nvidia-settings --query CurrentMetaMode | grep +3840; then
   nvidia-settings --assign CurrentMetaMode="$DVI, $HDMI"
   $polyrestart
   $notifyrestart
else
   nvidia-settings --assign CurrentMetaMode="$DVI, $HDMI, $TV"
   nitrogen --restore &>/dev/null &
   $polyrestart
   polybar tv -r &
   $notifyrestart
   xdotool mousemove --sync 4800 540
fi
