#!/bin/bash

enabled=$(nvidia-settings --query CurrentMetaMode | egrep -o "DPY-[0-9]")
connected=$(nvidia-settings -q dpys | grep "connected" | egrep -o "dpy:[0-9]")
screens=( "+1920+0" "+0+0" )
screens2=($enabled)

actions () {
	$HOME/.config/polybar/launch.sh &
	pkill xfce4-notifyd && /usr/lib/xfce4/notifyd/xfce4-notifyd &
	nitrogen --restore &
	[[ $(echo "$commands" | grep "+3840+0") ]] && \
	xdotool mousemove --sync 4800 540 || \
	xdotool mousemove --sync 2880 540
}

[[ $(echo "$enabled" | grep -c "DPY") -eq 2 ]] && \
[[ $(echo "$connected" | grep -c "dpy") -eq 3 ]] && \
screens+=( "+3840+0" )

for i in ${!screens[*]}; do
command="${screens2[i]}: nvidia-auto-select ${screens[i]} {ForceCompositionPipeline=On}"
screenlist+=("$command,")
done
commands=${screenlist[@]}
nvidia-settings --assign CurrentMetaMode="${commands%,}"
xset dpms force off
sleep 4
actions &>/dev/null &
